version: '3'
services:
  insightiq-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-insightiq-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_insightiq_api:/usr/lib/python3.6/site-packages/vlab_insightiq_api
    command: ["python3", "app.py"]

  insightiq-worker:
    image:
      willnx/vlab-insightiq-worker
    volumes:
      - ./vlab_insightiq_api:/usr/lib/python3.6/site-packages/vlab_insightiq_api
      - /mnt/raid/images/insightiq:/images:ro
    environment:
      - INF_VCENTER_SERVER=changeME
      - INF_VCENTER_USER=changeME
      - INF_VCENTER_PASSWORD=changeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  insightiq-broker:
    image:
      rabbitmq:3.7-alpine
